### ISSUE TITLE
Endless loop connecting to mpd server

### ISSUE THREAD

**Issue by chme** [sludgefeast/MPDroid#2]
Hi @sludgefeast 

really great that you tackled implementing better support for multiple mpd servers! 

I tried your development branch in the AndroidStudio VM and ran into an issue if the default mpd server is not reachable.

After opening the app the dialog "Connection Failed" pops up correctly. Clicking on the "Settings" button takes you to the ConnectionSettingsActivity. But it also instantly triggers the onResume() of this activity which tries to connect to the (unreachable) mpd server. The connection attempt fails and the "Connection Failed" dialog is shown once again.

Avoiding the connection attempt in onResume() in the ConnectionSettingsActivity seems to fix this.

**Comment by sludgefeast** [comment]
Hi @chme!
I fixed this issue. Thanks for your feedback. In the current phase there are still many issues left - so feel free to test, report or maybe fix some issues.

**Comment by chme** [comment]
I am sorry for taking so long to get back to you. Thanks for fixing this issue!
